### PR TITLE
Update danger deps to try and fix issues with Ruby 3.x

### PR DESCRIPTION
**Pull request by mscrivo**
as seen here: https://github.com/ruby-grape/grape-swagger-entity/actions/runs/7758689621/job/21161049669

### CODE REVIEW

**Comment by dblock** [comment]
Let's replace Travis CI with GHA first? Want to do it @mscrivo?

**Comment by dblock** [comment]
@mscrivo turn on actions in https://github.com/mscrivo/danger/actions and let's get a green build?

**Comment by mscrivo** [comment]
> @mscrivo turn on actions in [mscrivo/danger/actions](https://github.com/mscrivo/danger/actions) and let's get a green build?

it's there: https://github.com/mscrivo/danger/actions/runs/7759517933

**Comment by dblock** [comment]
Merged. Want to help co-maintain this? @mscrivo
If yes, drop me your rubygems username to dblock at dblock dot org.

**Comment by mscrivo** [comment]
> Merged. Want to help co-maintain this? @mscrivo If yes, drop me your rubygems username to dblock at dblock dot org.

sent

**Pull request merged**
